# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asrInterface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie


class Ui_MainWindow(object):
    def __init__(self, MainWindow):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_voice = QMovie("icon/voice.gif")
        self.gif_play = QMovie("icon/play.gif")
        self.voiceFig = QtWidgets.QLabel(self.centralwidget)
        self.playFig = QtWidgets.QLabel(self.centralwidget)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(314, 462)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.label_3.setGeometry(QtCore.QRect(60, 280, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 117, 210);")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_2.setGeometry(QtCore.QRect(60, 250, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 117, 210);")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.voiceFig.setGeometry(QtCore.QRect(70, 50, 161, 121))
        self.voiceFig.setText("")
        self.voiceFig.setMovie(self.gif_voice)
        self.gif_voice.start()
        self.voiceFig.setScaledContents(True)
        self.voiceFig.setObjectName("voiceFig")
        self.playFig.setGeometry(QtCore.QRect(70, 50, 161, 121))
        self.playFig.setText("")
        self.playFig.setMovie(self.gif_play)
        self.gif_play.start()
        self.playFig.setScaledContents(True)
        self.playFig.setObjectName("voicePlay")
        self.playFig.setVisible(False)

        self.label.setGeometry(QtCore.QRect(70, 170, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 117, 210);")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_5.setGeometry(QtCore.QRect(70, 190, 171, 65))
        font_5 = QtGui.QFont()
        font_5.setFamily("Calibri")
        font_5.setPointSize(14)
        font_5.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_5.setFont(font_5)
        self.label_5.setStyleSheet("color: rgb(255, 204, 0);")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_4.setGeometry(QtCore.QRect(60, 330, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 117, 210);")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_6.setGeometry(QtCore.QRect(60, 390, 231, 51))
        font_6 = QtGui.QFont()
        font_6.setFamily("Calibri")
        font_6.setPointSize(14)
        font_6.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_6.setFont(font_6)
        self.label_6.setStyleSheet("color: rgb(0, 117, 210);")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voice Assistant"))
        self.label_3.setText(_translate("MainWindow", "1. Enjoy music by saying \"Play music\""))
        self.label_2.setText(_translate("MainWindow", "You can:"))
        self.label.setText(_translate("MainWindow", "Hi! How can I help?"))
        self.label_4.setText(_translate("MainWindow", "2. Take some notes by saying \"Open Notepad\""))
        self.label_5.setText(_translate("MainWindow", "Press space key and then say something!"))
        self.label_6.setText(_translate("MainWindow", "3. Get the time by saying \"What's the time now\""))
